name: Project automations
on:
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request:
    types:
      - opened
      - reopened
      - review_requested
  pull_request_review:
    types:
      - 'submitted'

# map fields with customized labels
env:
  todo: ğŸ“š Backlog
  in_progress: ğŸ‘¨â€ğŸ’» In progress
  in_review: ğŸ‘€ In review
  changes_requested: ğŸ”„ Changes requested
  approved: ğŸ‘ Approved
  project_id: 2 # look at the URL of our GHP "Hibiscus"
  organization: HackSC

jobs:
  issue_opened_or_reopened:
    name: Move associated card to "${{ env.todo }}" if the issue is (re)opened
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Move card to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.BOT_GITHUB_PAT }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.issue.node_id }}
          status_value: ${{ env.todo }} # Target status
  pr_opened_or_reopened:
    name: Move associated card to "${{ env.in_progress }}" if PR is (re)opened
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - name: Mark PR status to ${{ env.in_progress }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.BOT_GITHUB_PAT }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_progress }} # Target status
  pr_reviewrequested:
    name: Move associated card to "${{ env.in_review }}" if review is requested on PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'review_requested'
    steps:
      - name: Mark PR status to ${{ env.in_review }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.BOT_GITHUB_PAT }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.in_review }} # Target status
  pr_changesrequested:
    name: Move associated card to "${{ env.changes_requested }}" if changes are requested on PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' && github.event.review.state == 'changes_requested'
    steps:
      - name: Mark PR status to ${{ env.changes_requested }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          gh_token: ${{ secrets.BOT_GITHUB_PAT }}
          organization: ${{ env.organization }}
          project_id: ${{ env.project_id }}
          resource_node_id: ${{ github.event.pull_request.node_id }}
          status_value: ${{ env.changes_requested }} # Target status
